AWSTemplateFormatVersion: "2010-09-09"
Transform: [AWS::Serverless-2016-10-31]
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StepEverywhere_example
      Runtime: go1.x
      Handler: example
      CodeUri: ./example
      MemorySize: 128
      Timeout: 30
